export { HomePage } from './HomePage'
export { AboutPage } from './AboutPage'
export { ListeningPage } from './ListeningPage'
export { ReadingPage } from './ReadingPage'
export { WritingPage } from './WritingPage'
export { SpeakingPage } from './SpeakingPage'
export { PracticePage } from './PracticePage'
export { ContactPage } from './ContactPage'
